import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import Question from "@/components/question";

const inter = Inter({ subsets: ["latin"] });

import fsPromises from "fs/promises";
import path from "path";
import { Key } from "react";

export default function Home(props: { ideo_vars: { title: string; question: string; all_answers: string[] }[] }) {
  const variables: { title: string; question: string; all_answers: string[] }[] = props.ideo_vars;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {variables.map((variable: { title: string; question: string; all_answers: string[] }) => (
          <Question
            key={variable.title}
            question={variable.question}
            options={variable.all_answers}
          />
        ))}
      </main>
    </>
  );
}

export async function getStaticProps() {
  const filePath = path.join(process.cwd(), "../json/ideo_vars.json");
  const jsonData = await fsPromises.readFile(filePath);
  const objectData = JSON.parse(jsonData.toString());

  return {
    props: objectData,
  };
}
